package com.example.wlplatform.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table function_info
 */
public class FunctionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   函数名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   函数描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_info.describe
     *
     * @mbg.generated
     */
    private String describe;

    /**
     * Database Column Remarks:
     *   函数适用位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_info.location
     *
     * @mbg.generated
     */
    private Byte location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_info.id
     *
     * @return the value of function_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_info.id
     *
     * @param id the value for function_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_info.name
     *
     * @return the value of function_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_info.name
     *
     * @param name the value for function_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_info.describe
     *
     * @return the value of function_info.describe
     *
     * @mbg.generated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_info.describe
     *
     * @param describe the value for function_info.describe
     *
     * @mbg.generated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_info.location
     *
     * @return the value of function_info.location
     *
     * @mbg.generated
     */
    public Byte getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_info.location
     *
     * @param location the value for function_info.location
     *
     * @mbg.generated
     */
    public void setLocation(Byte location) {
        this.location = location;
    }
}