package com.example.wlplatform.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table machine_info
 */
public class MachineInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: ip地址 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * Database Column Remarks: 端口 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.port
	 * @mbg.generated
	 */
	private Integer port;
	/**
	 * Database Column Remarks: 用户名 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.user
	 * @mbg.generated
	 */
	private String user;
	/**
	 * Database Column Remarks: 密码 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.passwd
	 * @mbg.generated
	 */
	private String passwd;
	/**
	 * Database Column Remarks: 环境名称 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.machine_name
	 * @mbg.generated
	 */
	private String machineName;
	/**
	 * Database Column Remarks: 环境类型 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.env_type
	 * @mbg.generated
	 */
	private Byte envType;
	/**
	 * Database Column Remarks: sa配置 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.sa_conf
	 * @mbg.generated
	 */
	private String saConf;
	/**
	 * Database Column Remarks: tux配置 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.tux_conf
	 * @mbg.generated
	 */
	private String tuxConf;
	/**
	 * Database Column Remarks: bip配置 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.bip_conf
	 * @mbg.generated
	 */
	private String bipConf;
	/**
	 * Database Column Remarks: 属组 This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.group_id
	 * @mbg.generated
	 */
	private Byte groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.pro_name
	 * @mbg.generated
	 */
	private String proName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column machine_info.protocol
	 * @mbg.generated
	 */
	private String protocol;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.id
	 * @return  the value of machine_info.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.id
	 * @param id  the value for machine_info.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.ip
	 * @return  the value of machine_info.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.ip
	 * @param ip  the value for machine_info.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.port
	 * @return  the value of machine_info.port
	 * @mbg.generated
	 */
	public Integer getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.port
	 * @param port  the value for machine_info.port
	 * @mbg.generated
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.user
	 * @return  the value of machine_info.user
	 * @mbg.generated
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.user
	 * @param user  the value for machine_info.user
	 * @mbg.generated
	 */
	public void setUser(String user) {
		this.user = user == null ? null : user.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.passwd
	 * @return  the value of machine_info.passwd
	 * @mbg.generated
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.passwd
	 * @param passwd  the value for machine_info.passwd
	 * @mbg.generated
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd == null ? null : passwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.machine_name
	 * @return  the value of machine_info.machine_name
	 * @mbg.generated
	 */
	public String getMachineName() {
		return machineName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.machine_name
	 * @param machineName  the value for machine_info.machine_name
	 * @mbg.generated
	 */
	public void setMachineName(String machineName) {
		this.machineName = machineName == null ? null : machineName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.env_type
	 * @return  the value of machine_info.env_type
	 * @mbg.generated
	 */
	public Byte getEnvType() {
		return envType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.env_type
	 * @param envType  the value for machine_info.env_type
	 * @mbg.generated
	 */
	public void setEnvType(Byte envType) {
		this.envType = envType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.sa_conf
	 * @return  the value of machine_info.sa_conf
	 * @mbg.generated
	 */
	public String getSaConf() {
		return saConf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.sa_conf
	 * @param saConf  the value for machine_info.sa_conf
	 * @mbg.generated
	 */
	public void setSaConf(String saConf) {
		this.saConf = saConf == null ? null : saConf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.tux_conf
	 * @return  the value of machine_info.tux_conf
	 * @mbg.generated
	 */
	public String getTuxConf() {
		return tuxConf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.tux_conf
	 * @param tuxConf  the value for machine_info.tux_conf
	 * @mbg.generated
	 */
	public void setTuxConf(String tuxConf) {
		this.tuxConf = tuxConf == null ? null : tuxConf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.bip_conf
	 * @return  the value of machine_info.bip_conf
	 * @mbg.generated
	 */
	public String getBipConf() {
		return bipConf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.bip_conf
	 * @param bipConf  the value for machine_info.bip_conf
	 * @mbg.generated
	 */
	public void setBipConf(String bipConf) {
		this.bipConf = bipConf == null ? null : bipConf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.group_id
	 * @return  the value of machine_info.group_id
	 * @mbg.generated
	 */
	public Byte getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.group_id
	 * @param groupId  the value for machine_info.group_id
	 * @mbg.generated
	 */
	public void setGroupId(Byte groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.pro_name
	 * @return  the value of machine_info.pro_name
	 * @mbg.generated
	 */
	public String getProName() {
		return proName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.pro_name
	 * @param proName  the value for machine_info.pro_name
	 * @mbg.generated
	 */
	public void setProName(String proName) {
		this.proName = proName == null ? null : proName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column machine_info.protocol
	 * @return  the value of machine_info.protocol
	 * @mbg.generated
	 */
	public String getProtocol() {
		return protocol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column machine_info.protocol
	 * @param protocol  the value for machine_info.protocol
	 * @mbg.generated
	 */
	public void setProtocol(String protocol) {
		this.protocol = protocol == null ? null : protocol.trim();
	}
}