package com.example.wlplatform.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.example.wlplatform.entity.CompileOption;
@Mapper  
public interface CompileOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compile_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compile_option
     *
     * @mbg.generated
     */
    int insert(CompileOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compile_option
     *
     * @mbg.generated
     */
    int insertSelective(CompileOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compile_option
     *
     * @mbg.generated
     */
    CompileOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compile_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompileOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compile_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompileOption record);
}