package com.example.wlplatform.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.example.wlplatform.entity.FunctionInfo;
@Mapper  
public interface FunctionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_info
     *
     * @mbg.generated
     */
    int insert(FunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_info
     *
     * @mbg.generated
     */
    int insertSelective(FunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_info
     *
     * @mbg.generated
     */
    FunctionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FunctionInfo record);
    
    List<FunctionInfo> selectAll();
}