package com.example.wlplatform.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.example.wlplatform.entity.MachineInfo;
@Mapper 
public interface MachineInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_info
	 * @mbg.generated
	 */
	int insert(MachineInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_info
	 * @mbg.generated
	 */
	int insertSelective(MachineInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_info
	 * @mbg.generated
	 */
	MachineInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MachineInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table machine_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MachineInfo record);

	List<MachineInfo> selectByGroupId(Integer group_id);
}